
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package kaskell;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 19;
  public static final int TIMES = 9;
  public static final int SEMICOLON = 6;
  public static final int VERT = 14;
  public static final int IDENT = 4;
  public static final int PLUS = 7;
  public static final int INT = 20;
  public static final int RBRACE = 3;
  public static final int LBRACK = 18;
  public static final int LBRACE = 2;
  public static final int LE = 12;
  public static final int EXP = 15;
  public static final int COMMA = 22;
  public static final int EOF = 0;
  public static final int DIV = 10;
  public static final int DOTS = 13;
  public static final int GE = 11;
  public static final int MINUS = 8;
  public static final int error = 1;
  public static final int EQ = 5;
  public static final int RPAR = 17;
  public static final int WHITE = 21;
  public static final int LPAR = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACE",
  "RBRACE",
  "IDENT",
  "EQ",
  "SEMICOLON",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "GE",
  "LE",
  "DOTS",
  "VERT",
  "EXP",
  "LPAR",
  "RPAR",
  "LBRACK",
  "RBRACK",
  "INT",
  "WHITE",
  "COMMA"
  };
}

